name = "XMag-Solarized"
license = "MIT"
licenselink = "https://github.com/AllanChain/hugo-xmag-solarized/blob/master/LICENSE.md"
description = "A solarized minimal magazine theme for Hugo, forked from hugo-xmag"
homepage = "https://github.com/AllanChain/hugo-xmag-solarized"
tags = ["minimal", "magazine", "clean", "simple", "minimalist", "blog", "responsive", "Google Analytics", "Gitalk", "Syntax Highlighting", "Solarized"]
features = ["blog", "magazine", "solarized"]
min_version = "0.62.0"

[author]
  name = "AllanChain"
  homepage = "https://allanchain.github.io/blog/"
  
[original]
  author = "Yihui Xie"
  homepage = "https://yihui.name"
  repo = "https://github.com/yihui/hugo-xmag"

